package com.sahed.money_tracker.util

import com.sahed.money_tracker.data.model.CountryCurrency
import com.sahed.money_tracker.data.model.CurrencyOption

object CountriesData {
    val countries: List<CountryCurrency> = listOf(
        CountryCurrency("AF", "Afghanistan", "🇦🇫", "AFN", "AFN"),
        CountryCurrency("AL", "Albania", "🇦🇱", "ALL", "ALL"),
        CountryCurrency("DZ", "Algeria", "🇩🇿", "DZD", "DA"),
        CountryCurrency("AS", "American Samoa", "🇦🇸", "USD", "$"),
        CountryCurrency("AD", "Andorra", "🇦🇩", "EUR", "€"),
        CountryCurrency("AO", "Angola", "🇦🇴", "AOA", "AOA"),
        CountryCurrency("AI", "Anguilla", "🇦🇮", "XCD", "EC$"),
        CountryCurrency("AQ", "Antarctica", "🇦🇶", "USD", "$"),
        CountryCurrency("AG", "Antigua & Barbuda", "🇦🇬", "XCD", "EC$"),
        CountryCurrency("AR", "Argentina", "🇦🇷", "ARS", "AR$"),
        CountryCurrency("AM", "Armenia", "🇦🇲", "AMD", "AMD"),
        CountryCurrency("AW", "Aruba", "🇦🇼", "AWG", "AWG"),
        CountryCurrency("AU", "Australia", "🇦🇺", "AUD", "A$"),
        CountryCurrency("AT", "Austria", "🇦🇹", "EUR", "€"),
        CountryCurrency("AZ", "Azerbaijan", "🇦🇿", "AZN", "AZN"),
        CountryCurrency("BS", "Bahamas", "🇧🇸", "BSD", "BSD"),
        CountryCurrency("BH", "Bahrain", "🇧🇭", "BHD", "BD"),
        CountryCurrency("BD", "Bangladesh", "🇧🇩", "BDT", "৳"),
        CountryCurrency("BB", "Barbados", "🇧🇧", "BBD", "BBD"),
        CountryCurrency("BY", "Belarus", "🇧🇾", "BYN", "BYN"),
        CountryCurrency("BE", "Belgium", "🇧🇪", "EUR", "€"),
        CountryCurrency("BZ", "Belize", "🇧🇿", "BZD", "BZD"),
        CountryCurrency("BJ", "Benin", "🇧🇯", "XOF", "F CFA"),
        CountryCurrency("BM", "Bermuda", "🇧🇲", "BMD", "BMD"),
        CountryCurrency("BT", "Bhutan", "🇧🇹", "BTN", "BTN"),
        CountryCurrency("BO", "Bolivia", "🇧🇴", "BOB", "BOB"),
        CountryCurrency("BA", "Bosnia & Herzegovina", "🇧🇦", "BAM", "BAM"),
        CountryCurrency("BW", "Botswana", "🇧🇼", "BWP", "BWP"),
        CountryCurrency("BV", "Bouvet Island", "🇧🇻", "NOK", "kr"),
        CountryCurrency("BR", "Brazil", "🇧🇷", "BRL", "R$"),
        CountryCurrency("IO", "British Indian Ocean Territory", "🇮🇴", "USD", "$"),
        CountryCurrency("VG", "British Virgin Islands", "🇻🇬", "USD", "$"),
        CountryCurrency("BN", "Brunei", "🇧🇳", "BND", "BND"),
        CountryCurrency("BG", "Bulgaria", "🇧🇬", "EUR", "€"),
        CountryCurrency("BF", "Burkina Faso", "🇧🇫", "XOF", "F CFA"),
        CountryCurrency("BI", "Burundi", "🇧🇮", "BIF", "BIF"),
        CountryCurrency("KH", "Cambodia", "🇰🇭", "KHR", "KHR"),
        CountryCurrency("CM", "Cameroon", "🇨🇲", "XAF", "FCFA"),
        CountryCurrency("CA", "Canada", "🇨🇦", "CAD", "CA$"),
        CountryCurrency("CV", "Cape Verde", "🇨🇻", "CVE", "CVE"),
        CountryCurrency("BQ", "Caribbean Netherlands", "🇧🇶", "USD", "$"),
        CountryCurrency("KY", "Cayman Islands", "🇰🇾", "KYD", "KYD"),
        CountryCurrency("CF", "Central African Republic", "🇨🇫", "XAF", "FCFA"),
        CountryCurrency("TD", "Chad", "🇹🇩", "XAF", "FCFA"),
        CountryCurrency("CL", "Chile", "🇨🇱", "CLP", "CLP$"),
        CountryCurrency("CN", "China", "🇨🇳", "CNY", "¥"),
        CountryCurrency("CX", "Christmas Island", "🇨🇽", "AUD", "A$"),
        CountryCurrency("CC", "Cocos (Keeling) Islands", "🇨🇨", "AUD", "A$"),
        CountryCurrency("CO", "Colombia", "🇨🇴", "COP", "COL$"),
        CountryCurrency("KM", "Comoros", "🇰🇲", "KMF", "KMF"),
        CountryCurrency("CG", "Congo - Brazzaville", "🇨🇬", "XAF", "FCFA"),
        CountryCurrency("CD", "Congo - Kinshasa", "🇨🇩", "CDF", "CDF"),
        CountryCurrency("CK", "Cook Islands", "🇨🇰", "NZD", "NZ$"),
        CountryCurrency("CR", "Costa Rica", "🇨🇷", "CRC", "CRC"),
        CountryCurrency("HR", "Croatia", "🇭🇷", "EUR", "€"),
        CountryCurrency("CU", "Cuba", "🇨🇺", "CUP", "CUP"),
        CountryCurrency("CW", "Curaçao", "🇨🇼", "XCG", "Cg."),
        CountryCurrency("CY", "Cyprus", "🇨🇾", "EUR", "€"),
        CountryCurrency("CZ", "Czechia", "🇨🇿", "CZK", "Kč"),
        CountryCurrency("CI", "Côte d’Ivoire", "🇨🇮", "XOF", "F CFA"),
        CountryCurrency("DK", "Denmark", "🇩🇰", "DKK", "kr"),
        CountryCurrency("DJ", "Djibouti", "🇩🇯", "DJF", "DJF"),
        CountryCurrency("DM", "Dominica", "🇩🇲", "XCD", "EC$"),
        CountryCurrency("DO", "Dominican Republic", "🇩🇴", "DOP", "DOP"),
        CountryCurrency("EC", "Ecuador", "🇪🇨", "USD", "$"),
        CountryCurrency("EG", "Egypt", "🇪🇬", "EGP", "E£"),
        CountryCurrency("SV", "El Salvador", "🇸🇻", "SVC", "SVC"),
        CountryCurrency("GQ", "Equatorial Guinea", "🇬🇶", "XAF", "FCFA"),
        CountryCurrency("ER", "Eritrea", "🇪🇷", "ERN", "ERN"),
        CountryCurrency("EE", "Estonia", "🇪🇪", "EUR", "€"),
        CountryCurrency("SZ", "Eswatini", "🇸🇿", "SZL", "SZL"),
        CountryCurrency("ET", "Ethiopia", "🇪🇹", "ETB", "ETB"),
        CountryCurrency("EU", "Eurozone", "🇪🇺", "EUR", "€"),
        CountryCurrency("FK", "Falkland Islands", "🇫🇰", "FKP", "FKP"),
        CountryCurrency("FO", "Faroe Islands", "🇫🇴", "DKK", "kr"),
        CountryCurrency("FJ", "Fiji", "🇫🇯", "FJD", "FJD"),
        CountryCurrency("FI", "Finland", "🇫🇮", "EUR", "€"),
        CountryCurrency("FR", "France", "🇫🇷", "EUR", "€"),
        CountryCurrency("GF", "French Guiana", "🇬🇫", "EUR", "€"),
        CountryCurrency("PF", "French Polynesia", "🇵🇫", "XPF", "CFPF"),
        CountryCurrency("TF", "French Southern Territories", "🇹🇫", "EUR", "€"),
        CountryCurrency("GA", "Gabon", "🇬🇦", "XAF", "FCFA"),
        CountryCurrency("GM", "Gambia", "🇬🇲", "GMD", "GMD"),
        CountryCurrency("GE", "Georgia", "🇬🇪", "GEL", "GEL"),
        CountryCurrency("DE", "Germany", "🇩🇪", "EUR", "€"),
        CountryCurrency("GH", "Ghana", "🇬🇭", "GHS", "GH₵"),
        CountryCurrency("GI", "Gibraltar", "🇬🇮", "GIP", "GIP"),
        CountryCurrency("GR", "Greece", "🇬🇷", "EUR", "€"),
        CountryCurrency("GL", "Greenland", "🇬🇱", "DKK", "kr"),
        CountryCurrency("GD", "Grenada", "🇬🇩", "XCD", "EC$"),
        CountryCurrency("GP", "Guadeloupe", "🇬🇵", "EUR", "€"),
        CountryCurrency("GU", "Guam", "🇬🇺", "USD", "$"),
        CountryCurrency("GT", "Guatemala", "🇬🇹", "GTQ", "GTQ"),
        CountryCurrency("GG", "Guernsey", "🇬🇬", "GBP", "£"),
        CountryCurrency("GN", "Guinea", "🇬🇳", "GNF", "GNF"),
        CountryCurrency("GW", "Guinea-Bissau", "🇬🇼", "XOF", "F CFA"),
        CountryCurrency("GY", "Guyana", "🇬🇾", "GYD", "GYD"),
        CountryCurrency("HT", "Haiti", "🇭🇹", "HTG", "HTG"),
        CountryCurrency("HM", "Heard & McDonald Islands", "🇭🇲", "AUD", "A$"),
        CountryCurrency("HN", "Honduras", "🇭🇳", "HNL", "HNL"),
        CountryCurrency("HK", "Hong Kong SAR China", "🇭🇰", "HKD", "HK$"),
        CountryCurrency("HU", "Hungary", "🇭🇺", "HUF", "Ft"),
        CountryCurrency("IS", "Iceland", "🇮🇸", "ISK", "ISK"),
        CountryCurrency("IN", "India", "🇮🇳", "INR", "₹"),
        CountryCurrency("ID", "Indonesia", "🇮🇩", "IDR", "Rp"),
        CountryCurrency("IR", "Iran", "🇮🇷", "IRR", "IRR"),
        CountryCurrency("IQ", "Iraq", "🇮🇶", "IQD", "ID"),
        CountryCurrency("IE", "Ireland", "🇮🇪", "EUR", "€"),
        CountryCurrency("IM", "Isle of Man", "🇮🇲", "GBP", "£"),
        CountryCurrency("IL", "Israel", "🇮🇱", "ILS", "₪"),
        CountryCurrency("IT", "Italy", "🇮🇹", "EUR", "€"),
        CountryCurrency("JM", "Jamaica", "🇯🇲", "JMD", "JMD"),
        CountryCurrency("JP", "Japan", "🇯🇵", "JPY", "¥"),
        CountryCurrency("JE", "Jersey", "🇯🇪", "GBP", "£"),
        CountryCurrency("JO", "Jordan", "🇯🇴", "JOD", "JD"),
        CountryCurrency("KZ", "Kazakhstan", "🇰🇿", "KZT", "₸"),
        CountryCurrency("KE", "Kenya", "🇰🇪", "KES", "KSh"),
        CountryCurrency("KI", "Kiribati", "🇰🇮", "AUD", "A$"),
        CountryCurrency("KW", "Kuwait", "🇰🇼", "KWD", "د.ك"),
        CountryCurrency("KG", "Kyrgyzstan", "🇰🇬", "KGS", "KGS"),
        CountryCurrency("LA", "Laos", "🇱🇦", "LAK", "LAK"),
        CountryCurrency("LV", "Latvia", "🇱🇻", "EUR", "€"),
        CountryCurrency("LB", "Lebanon", "🇱🇧", "LBP", "L£"),
        CountryCurrency("LS", "Lesotho", "🇱🇸", "LSL", "LSL"),
        CountryCurrency("LR", "Liberia", "🇱🇷", "LRD", "LRD"),
        CountryCurrency("LY", "Libya", "🇱🇾", "LYD", "LYD"),
        CountryCurrency("LI", "Liechtenstein", "🇱🇮", "CHF", "CHF"),
        CountryCurrency("LT", "Lithuania", "🇱🇹", "EUR", "€"),
        CountryCurrency("LU", "Luxembourg", "🇱🇺", "EUR", "€"),
        CountryCurrency("MO", "Macao SAR China", "🇲🇴", "MOP", "MOP"),
        CountryCurrency("MG", "Madagascar", "🇲🇬", "MGA", "MGA"),
        CountryCurrency("MW", "Malawi", "🇲🇼", "MWK", "MWK"),
        CountryCurrency("MY", "Malaysia", "🇲🇾", "MYR", "RM"),
        CountryCurrency("MV", "Maldives", "🇲🇻", "MVR", "MVR"),
        CountryCurrency("ML", "Mali", "🇲🇱", "XOF", "F CFA"),
        CountryCurrency("MT", "Malta", "🇲🇹", "EUR", "€"),
        CountryCurrency("MH", "Marshall Islands", "🇲🇭", "USD", "$"),
        CountryCurrency("MQ", "Martinique", "🇲🇶", "EUR", "€"),
        CountryCurrency("MR", "Mauritania", "🇲🇷", "MRU", "MRU"),
        CountryCurrency("MU", "Mauritius", "🇲🇺", "MUR", "MUR"),
        CountryCurrency("YT", "Mayotte", "🇾🇹", "EUR", "€"),
        CountryCurrency("MX", "Mexico", "🇲🇽", "MXN", "MX$"),
        CountryCurrency("FM", "Micronesia", "🇫🇲", "USD", "$"),
        CountryCurrency("MD", "Moldova", "🇲🇩", "MDL", "MDL"),
        CountryCurrency("MC", "Monaco", "🇲🇨", "EUR", "€"),
        CountryCurrency("MN", "Mongolia", "🇲🇳", "MNT", "MNT"),
        CountryCurrency("ME", "Montenegro", "🇲🇪", "EUR", "€"),
        CountryCurrency("MS", "Montserrat", "🇲🇸", "XCD", "EC$"),
        CountryCurrency("MA", "Morocco", "🇲🇦", "MAD", "DH"),
        CountryCurrency("MZ", "Mozambique", "🇲🇿", "MZN", "MZN"),
        CountryCurrency("MM", "Myanmar (Burma)", "🇲🇲", "MMK", "MMK"),
        CountryCurrency("NA", "Namibia", "🇳🇦", "NAD", "NAD"),
        CountryCurrency("NR", "Nauru", "🇳🇷", "AUD", "A$"),
        CountryCurrency("NP", "Nepal", "🇳🇵", "NPR", "₨"),
        CountryCurrency("NL", "Netherlands", "🇳🇱", "EUR", "€"),
        CountryCurrency("NC", "New Caledonia", "🇳🇨", "XPF", "CFPF"),
        CountryCurrency("NZ", "New Zealand", "🇳🇿", "NZD", "NZ$"),
        CountryCurrency("NI", "Nicaragua", "🇳🇮", "NIO", "NIO"),
        CountryCurrency("NE", "Niger", "🇳🇪", "XOF", "F CFA"),
        CountryCurrency("NG", "Nigeria", "🇳🇬", "NGN", "₦"),
        CountryCurrency("NU", "Niue", "🇳🇺", "NZD", "NZ$"),
        CountryCurrency("NF", "Norfolk Island", "🇳🇫", "AUD", "A$"),
        CountryCurrency("KP", "North Korea", "🇰🇵", "KPW", "KPW"),
        CountryCurrency("MK", "North Macedonia", "🇲🇰", "MKD", "MKD"),
        CountryCurrency("MP", "Northern Mariana Islands", "🇲🇵", "USD", "$"),
        CountryCurrency("NO", "Norway", "🇳🇴", "NOK", "kr"),
        CountryCurrency("OM", "Oman", "🇴🇲", "OMR", "ر.ع."),
        CountryCurrency("PK", "Pakistan", "🇵🇰", "PKR", "₨"),
        CountryCurrency("PW", "Palau", "🇵🇼", "USD", "$"),
        CountryCurrency("PS", "Palestinian Territories", "🇵🇸", "ILS", "₪"),
        CountryCurrency("PA", "Panama", "🇵🇦", "PAB", "PAB"),
        CountryCurrency("PG", "Papua New Guinea", "🇵🇬", "PGK", "PGK"),
        CountryCurrency("PY", "Paraguay", "🇵🇾", "PYG", "PYG"),
        CountryCurrency("PE", "Peru", "🇵🇪", "PEN", "S/."),
        CountryCurrency("PH", "Philippines", "🇵🇭", "PHP", "₱"),
        CountryCurrency("PN", "Pitcairn Islands", "🇵🇳", "NZD", "NZ$"),
        CountryCurrency("PL", "Poland", "🇵🇱", "PLN", "zł"),
        CountryCurrency("PT", "Portugal", "🇵🇹", "EUR", "€"),
        CountryCurrency("PR", "Puerto Rico", "🇵🇷", "USD", "$"),
        CountryCurrency("QA", "Qatar", "🇶🇦", "QAR", "ر.ق"),
        CountryCurrency("RO", "Romania", "🇷🇴", "RON", "lei"),
        CountryCurrency("RU", "Russia", "🇷🇺", "RUB", "₽"),
        CountryCurrency("RW", "Rwanda", "🇷🇼", "RWF", "RWF"),
        CountryCurrency("RE", "Réunion", "🇷🇪", "EUR", "€"),
        CountryCurrency("WS", "Samoa", "🇼🇸", "WST", "WST"),
        CountryCurrency("SM", "San Marino", "🇸🇲", "EUR", "€"),
        CountryCurrency("SA", "Saudi Arabia", "🇸🇦", "SAR", "﷼"),
        CountryCurrency("SN", "Senegal", "🇸🇳", "XOF", "F CFA"),
        CountryCurrency("RS", "Serbia", "🇷🇸", "RSD", "RSD"),
        CountryCurrency("SC", "Seychelles", "🇸🇨", "SCR", "SCR"),
        CountryCurrency("SL", "Sierra Leone", "🇸🇱", "SLE", "SLE"),
        CountryCurrency("SG", "Singapore", "🇸🇬", "SGD", "S$"),
        CountryCurrency("SX", "Sint Maarten", "🇸🇽", "XCG", "Cg."),
        CountryCurrency("SK", "Slovakia", "🇸🇰", "EUR", "€"),
        CountryCurrency("SI", "Slovenia", "🇸🇮", "EUR", "€"),
        CountryCurrency("SB", "Solomon Islands", "🇸🇧", "SBD", "SBD"),
        CountryCurrency("SO", "Somalia", "🇸🇴", "SOS", "SOS"),
        CountryCurrency("ZA", "South Africa", "🇿🇦", "ZAR", "R"),
        CountryCurrency("GS", "South Georgia & South Sandwich Islands", "🇬🇸", "GBP", "£"),
        CountryCurrency("KR", "South Korea", "🇰🇷", "KRW", "₩"),
        CountryCurrency("SS", "South Sudan", "🇸🇸", "SSP", "SSP"),
        CountryCurrency("ES", "Spain", "🇪🇸", "EUR", "€"),
        CountryCurrency("LK", "Sri Lanka", "🇱🇰", "LKR", "Rs"),
        CountryCurrency("BL", "St. Barthélemy", "🇧🇱", "EUR", "€"),
        CountryCurrency("SH", "St. Helena", "🇸🇭", "SHP", "SHP"),
        CountryCurrency("KN", "St. Kitts & Nevis", "🇰🇳", "XCD", "EC$"),
        CountryCurrency("LC", "St. Lucia", "🇱🇨", "XCD", "EC$"),
        CountryCurrency("MF", "St. Martin", "🇲🇫", "EUR", "€"),
        CountryCurrency("PM", "St. Pierre & Miquelon", "🇵🇲", "EUR", "€"),
        CountryCurrency("VC", "St. Vincent & Grenadines", "🇻🇨", "XCD", "EC$"),
        CountryCurrency("SD", "Sudan", "🇸🇩", "SDG", "SDG"),
        CountryCurrency("SR", "Suriname", "🇸🇷", "SRD", "SRD"),
        CountryCurrency("SJ", "Svalbard & Jan Mayen", "🇸🇯", "NOK", "kr"),
        CountryCurrency("SE", "Sweden", "🇸🇪", "SEK", "kr"),
        CountryCurrency("CH", "Switzerland", "🇨🇭", "CHF", "CHF"),
        CountryCurrency("SY", "Syria", "🇸🇾", "SYP", "SYP"),
        CountryCurrency("ST", "São Tomé & Príncipe", "🇸🇹", "STN", "STN"),
        CountryCurrency("TW", "Taiwan", "🇹🇼", "TWD", "NT$"),
        CountryCurrency("TJ", "Tajikistan", "🇹🇯", "TJS", "TJS"),
        CountryCurrency("TZ", "Tanzania", "🇹🇿", "TZS", "TZS"),
        CountryCurrency("TH", "Thailand", "🇹🇭", "THB", "฿"),
        CountryCurrency("TL", "Timor-Leste", "🇹🇱", "USD", "$"),
        CountryCurrency("TG", "Togo", "🇹🇬", "XOF", "F CFA"),
        CountryCurrency("TK", "Tokelau", "🇹🇰", "NZD", "NZ$"),
        CountryCurrency("TO", "Tonga", "🇹🇴", "TOP", "TOP"),
        CountryCurrency("TT", "Trinidad & Tobago", "🇹🇹", "TTD", "TTD"),
        CountryCurrency("TN", "Tunisia", "🇹🇳", "TND", "DT"),
        CountryCurrency("TM", "Turkmenistan", "🇹🇲", "TMT", "TMT"),
        CountryCurrency("TC", "Turks & Caicos Islands", "🇹🇨", "USD", "$"),
        CountryCurrency("TV", "Tuvalu", "🇹🇻", "AUD", "A$"),
        CountryCurrency("TR", "Türkiye", "🇹🇷", "TRY", "₺"),
        CountryCurrency("UM", "U.S. Outlying Islands", "🇺🇲", "USD", "$"),
        CountryCurrency("VI", "U.S. Virgin Islands", "🇻🇮", "USD", "$"),
        CountryCurrency("UG", "Uganda", "🇺🇬", "UGX", "UGX"),
        CountryCurrency("UA", "Ukraine", "🇺🇦", "UAH", "₴"),
        CountryCurrency("AE", "United Arab Emirates", "🇦🇪", "AED", "د.إ"),
        CountryCurrency("GB", "United Kingdom", "🇬🇧", "GBP", "£"),
        CountryCurrency("US", "United States", "🇺🇸", "USD", "$"),
        CountryCurrency("UY", "Uruguay", "🇺🇾", "UYU", "UYU"),
        CountryCurrency("UZ", "Uzbekistan", "🇺🇿", "UZS", "UZS"),
        CountryCurrency("VU", "Vanuatu", "🇻🇺", "VUV", "VUV"),
        CountryCurrency("VA", "Vatican City", "🇻🇦", "EUR", "€"),
        CountryCurrency("VE", "Venezuela", "🇻🇪", "VES", "VES"),
        CountryCurrency("VN", "Vietnam", "🇻🇳", "VND", "₫"),
        CountryCurrency("WF", "Wallis & Futuna", "🇼🇫", "XPF", "CFPF"),
        CountryCurrency("EH", "Western Sahara", "🇪🇭", "MAD", "DH"),
        CountryCurrency("YE", "Yemen", "🇾🇪", "YER", "YER"),
        CountryCurrency("ZM", "Zambia", "🇿🇲", "ZMW", "ZMW"),
        CountryCurrency("ZW", "Zimbabwe", "🇿🇼", "ZWG", "ZWG"),
        CountryCurrency("AX", "Åland Islands", "🇦🇽", "EUR", "€")
    )

    val popularCurrencies: List<CurrencyOption> = listOf(
        CurrencyOption("USD", "$", "US Dollar"),
        CurrencyOption("BDT", "৳", "Bangladeshi Taka"),
        CurrencyOption("EUR", "€", "Euro"),
        CurrencyOption("GBP", "£", "British Pound"),
        CurrencyOption("CAD", "CA$", "Canadian Dollar"),
        CurrencyOption("AUD", "A$", "Australian Dollar"),
        CurrencyOption("AED", "د.إ", "United Arab Emirates Dirham"),
        CurrencyOption("SAR", "﷼", "Saudi Riyal"),
        CurrencyOption("INR", "₹", "Indian Rupee"),
        CurrencyOption("SGD", "S$", "Singapore Dollar"),
        CurrencyOption("MYR", "RM", "Malaysian Ringgit"),
        CurrencyOption("JPY", "¥", "Japanese Yen"),
        CurrencyOption("CHF", "CHF", "Swiss Franc"),
        CurrencyOption("CNY", "¥", "Chinese Yuan"),
        CurrencyOption("QAR", "ر.ق", "Qatari Riyal"),
        CurrencyOption("KWD", "د.ك", "Kuwaiti Dinar"),
        CurrencyOption("TRY", "₺", "Turkish Lira"),
        CurrencyOption("PKR", "₨", "Pakistani Rupee"),
        CurrencyOption("NGN", "₦", "Nigerian Naira"),
        CurrencyOption("ZAR", "R", "South African Rand"),
        CurrencyOption("BRL", "R$", "Brazilian Real"),
        CurrencyOption("THB", "฿", "Thai Baht"),
        CurrencyOption("IDR", "Rp", "Indonesian Rupiah"),
        CurrencyOption("PHP", "₱", "Philippine Peso"),
        CurrencyOption("NZD", "NZ$", "New Zealand Dollar"),
        CurrencyOption("KRW", "₩", "South Korean Won"),
        CurrencyOption("VND", "₫", "Vietnamese Dong"),
        CurrencyOption("RUB", "₽", "Russian Ruble"),
        CurrencyOption("EGP", "E£", "Egyptian Pound"),
        CurrencyOption("MXN", "MX$", "Mexican Peso")
    )

    val allCurrencies: List<CurrencyOption> = listOf(
        CurrencyOption("ADP", "ADP", "Andorran Peseta"),
        CurrencyOption("AED", "د.إ", "United Arab Emirates Dirham"),
        CurrencyOption("AFN", "AFN", "Afghan Afghani"),
        CurrencyOption("ALL", "ALL", "Albanian Lek"),
        CurrencyOption("AMD", "AMD", "Armenian Dram"),
        CurrencyOption("ANG", "ANG", "Netherlands Antillean Guilder"),
        CurrencyOption("AOA", "AOA", "Angolan Kwanza"),
        CurrencyOption("ARS", "AR$", "Argentine Peso"),
        CurrencyOption("ATS", "ATS", "Austrian Schilling"),
        CurrencyOption("AUD", "A$", "Australian Dollar"),
        CurrencyOption("AWG", "AWG", "Aruban Florin"),
        CurrencyOption("AYM", "AYM", "AYM"),
        CurrencyOption("AZN", "AZN", "Azerbaijani Manat"),
        CurrencyOption("BAM", "BAM", "Bosnia-Herzegovina Convertible Mark"),
        CurrencyOption("BBD", "BBD", "Barbadian Dollar"),
        CurrencyOption("BDT", "৳", "Bangladeshi Taka"),
        CurrencyOption("BEF", "BEF", "Belgian Franc"),
        CurrencyOption("BGL", "BGL", "Bulgarian Hard Lev"),
        CurrencyOption("BGN", "лв", "Bulgarian Lev"),
        CurrencyOption("BHD", "BD", "Bahraini Dinar"),
        CurrencyOption("BIF", "BIF", "Burundian Franc"),
        CurrencyOption("BMD", "BMD", "Bermudan Dollar"),
        CurrencyOption("BND", "BND", "Brunei Dollar"),
        CurrencyOption("BOB", "BOB", "Bolivian Boliviano"),
        CurrencyOption("BOV", "BOV", "Bolivian Mvdol"),
        CurrencyOption("BRL", "R$", "Brazilian Real"),
        CurrencyOption("BSD", "BSD", "Bahamian Dollar"),
        CurrencyOption("BTN", "BTN", "Bhutanese Ngultrum"),
        CurrencyOption("BWP", "BWP", "Botswanan Pula"),
        CurrencyOption("BYN", "BYN", "Belarusian Ruble"),
        CurrencyOption("BZD", "BZD", "Belize Dollar"),
        CurrencyOption("CAD", "CA$", "Canadian Dollar"),
        CurrencyOption("CDF", "CDF", "Congolese Franc"),
        CurrencyOption("CHE", "CHE", "WIR Euro"),
        CurrencyOption("CHF", "CHF", "Swiss Franc"),
        CurrencyOption("CHW", "CHW", "WIR Franc"),
        CurrencyOption("CLF", "CLF", "Chilean Unit of Account (UF)"),
        CurrencyOption("CLP", "CLP$", "Chilean Peso"),
        CurrencyOption("CNY", "¥", "Chinese Yuan"),
        CurrencyOption("COP", "COL$", "Colombian Peso"),
        CurrencyOption("COU", "COU", "Colombian Real Value Unit"),
        CurrencyOption("CRC", "CRC", "Costa Rican Colón"),
        CurrencyOption("CUC", "CUC", "Cuban Convertible Peso"),
        CurrencyOption("CUP", "CUP", "Cuban Peso"),
        CurrencyOption("CVE", "CVE", "Cape Verdean Escudo"),
        CurrencyOption("CYP", "CYP", "Cypriot Pound"),
        CurrencyOption("CZK", "Kč", "Czech Koruna"),
        CurrencyOption("DEM", "DEM", "German Mark"),
        CurrencyOption("DJF", "DJF", "Djiboutian Franc"),
        CurrencyOption("DKK", "kr", "Danish Krone"),
        CurrencyOption("DOP", "DOP", "Dominican Peso"),
        CurrencyOption("DZD", "DA", "Algerian Dinar"),
        CurrencyOption("EEK", "EEK", "Estonian Kroon"),
        CurrencyOption("EGP", "E£", "Egyptian Pound"),
        CurrencyOption("ERN", "ERN", "Eritrean Nakfa"),
        CurrencyOption("ESP", "ESP", "Spanish Peseta"),
        CurrencyOption("ETB", "ETB", "Ethiopian Birr"),
        CurrencyOption("EUR", "€", "Euro"),
        CurrencyOption("FIM", "FIM", "Finnish Markka"),
        CurrencyOption("FJD", "FJD", "Fijian Dollar"),
        CurrencyOption("FKP", "FKP", "Falkland Islands Pound"),
        CurrencyOption("FRF", "FRF", "French Franc"),
        CurrencyOption("GBP", "£", "British Pound"),
        CurrencyOption("GEL", "GEL", "Georgian Lari"),
        CurrencyOption("GHS", "GH₵", "Ghanaian Cedi"),
        CurrencyOption("GIP", "GIP", "Gibraltar Pound"),
        CurrencyOption("GMD", "GMD", "Gambian Dalasi"),
        CurrencyOption("GNF", "GNF", "Guinean Franc"),
        CurrencyOption("GRD", "GRD", "Greek Drachma"),
        CurrencyOption("GTQ", "GTQ", "Guatemalan Quetzal"),
        CurrencyOption("GWP", "GWP", "Guinea-Bissau Peso"),
        CurrencyOption("GYD", "GYD", "Guyanaese Dollar"),
        CurrencyOption("HKD", "HK$", "Hong Kong Dollar"),
        CurrencyOption("HNL", "HNL", "Honduran Lempira"),
        CurrencyOption("HRK", "HRK", "Croatian Kuna"),
        CurrencyOption("HTG", "HTG", "Haitian Gourde"),
        CurrencyOption("HUF", "Ft", "Hungarian Forint"),
        CurrencyOption("IDR", "Rp", "Indonesian Rupiah"),
        CurrencyOption("IEP", "IEP", "Irish Pound"),
        CurrencyOption("ILS", "₪", "Israeli New Shekel"),
        CurrencyOption("INR", "₹", "Indian Rupee"),
        CurrencyOption("IQD", "ID", "Iraqi Dinar"),
        CurrencyOption("IRR", "IRR", "Iranian Rial"),
        CurrencyOption("ISK", "ISK", "Icelandic Króna"),
        CurrencyOption("ITL", "ITL", "Italian Lira"),
        CurrencyOption("JMD", "JMD", "Jamaican Dollar"),
        CurrencyOption("JOD", "JD", "Jordanian Dinar"),
        CurrencyOption("JPY", "¥", "Japanese Yen"),
        CurrencyOption("KES", "KSh", "Kenyan Shilling"),
        CurrencyOption("KGS", "KGS", "Kyrgystani Som"),
        CurrencyOption("KHR", "KHR", "Cambodian Riel"),
        CurrencyOption("KMF", "KMF", "Comorian Franc"),
        CurrencyOption("KPW", "KPW", "North Korean Won"),
        CurrencyOption("KRW", "₩", "South Korean Won"),
        CurrencyOption("KWD", "د.ك", "Kuwaiti Dinar"),
        CurrencyOption("KYD", "KYD", "Cayman Islands Dollar"),
        CurrencyOption("KZT", "₸", "Kazakhstani Tenge"),
        CurrencyOption("LAK", "LAK", "Laotian Kip"),
        CurrencyOption("LBP", "L£", "Lebanese Pound"),
        CurrencyOption("LKR", "Rs", "Sri Lankan Rupee"),
        CurrencyOption("LRD", "LRD", "Liberian Dollar"),
        CurrencyOption("LSL", "LSL", "Lesotho Loti"),
        CurrencyOption("LTL", "LTL", "Lithuanian Litas"),
        CurrencyOption("LUF", "LUF", "Luxembourgian Franc"),
        CurrencyOption("LVL", "LVL", "Latvian Lats"),
        CurrencyOption("LYD", "LYD", "Libyan Dinar"),
        CurrencyOption("MAD", "DH", "Moroccan Dirham"),
        CurrencyOption("MDL", "MDL", "Moldovan Leu"),
        CurrencyOption("MGA", "MGA", "Malagasy Ariary"),
        CurrencyOption("MGF", "MGF", "Malagasy Franc"),
        CurrencyOption("MKD", "MKD", "Macedonian Denar"),
        CurrencyOption("MMK", "MMK", "Myanmar Kyat"),
        CurrencyOption("MNT", "MNT", "Mongolian Tugrik"),
        CurrencyOption("MOP", "MOP", "Macanese Pataca"),
        CurrencyOption("MRU", "MRU", "Mauritanian Ouguiya"),
        CurrencyOption("MTL", "MTL", "Maltese Lira"),
        CurrencyOption("MUR", "MUR", "Mauritian Rupee"),
        CurrencyOption("MVR", "MVR", "Maldivian Rufiyaa"),
        CurrencyOption("MWK", "MWK", "Malawian Kwacha"),
        CurrencyOption("MXN", "MX$", "Mexican Peso"),
        CurrencyOption("MXV", "MXV", "Mexican Investment Unit"),
        CurrencyOption("MYR", "RM", "Malaysian Ringgit"),
        CurrencyOption("MZN", "MZN", "Mozambican Metical"),
        CurrencyOption("NAD", "NAD", "Namibian Dollar"),
        CurrencyOption("NGN", "₦", "Nigerian Naira"),
        CurrencyOption("NIO", "NIO", "Nicaraguan Córdoba"),
        CurrencyOption("NLG", "NLG", "Dutch Guilder"),
        CurrencyOption("NOK", "kr", "Norwegian Krone"),
        CurrencyOption("NPR", "₨", "Nepalese Rupee"),
        CurrencyOption("NZD", "NZ$", "New Zealand Dollar"),
        CurrencyOption("OMR", "ر.ع.", "Omani Rial"),
        CurrencyOption("PAB", "PAB", "Panamanian Balboa"),
        CurrencyOption("PEN", "S/.", "Peruvian Sol"),
        CurrencyOption("PGK", "PGK", "Papua New Guinean Kina"),
        CurrencyOption("PHP", "₱", "Philippine Peso"),
        CurrencyOption("PKR", "₨", "Pakistani Rupee"),
        CurrencyOption("PLN", "zł", "Polish Zloty"),
        CurrencyOption("PTE", "PTE", "Portuguese Escudo"),
        CurrencyOption("PYG", "PYG", "Paraguayan Guarani"),
        CurrencyOption("QAR", "ر.ق", "Qatari Riyal"),
        CurrencyOption("RON", "lei", "Romanian Leu"),
        CurrencyOption("RSD", "RSD", "Serbian Dinar"),
        CurrencyOption("RUB", "₽", "Russian Ruble"),
        CurrencyOption("RWF", "RWF", "Rwandan Franc"),
        CurrencyOption("SAR", "﷼", "Saudi Riyal"),
        CurrencyOption("SBD", "SBD", "Solomon Islands Dollar"),
        CurrencyOption("SCR", "SCR", "Seychellois Rupee"),
        CurrencyOption("SDG", "SDG", "Sudanese Pound"),
        CurrencyOption("SEK", "kr", "Swedish Krona"),
        CurrencyOption("SGD", "S$", "Singapore Dollar"),
        CurrencyOption("SHP", "SHP", "St. Helena Pound"),
        CurrencyOption("SIT", "SIT", "Slovenian Tolar"),
        CurrencyOption("SKK", "SKK", "Slovak Koruna"),
        CurrencyOption("SLE", "SLE", "Sierra Leonean Leone"),
        CurrencyOption("SLL", "SLL", "Sierra Leonean Leone (1964—2022)"),
        CurrencyOption("SOS", "SOS", "Somali Shilling"),
        CurrencyOption("SRD", "SRD", "Surinamese Dollar"),
        CurrencyOption("SRG", "SRG", "Surinamese Guilder"),
        CurrencyOption("SSP", "SSP", "South Sudanese Pound"),
        CurrencyOption("STN", "STN", "São Tomé & Príncipe Dobra"),
        CurrencyOption("SVC", "SVC", "Salvadoran Colón"),
        CurrencyOption("SYP", "SYP", "Syrian Pound"),
        CurrencyOption("SZL", "SZL", "Swazi Lilangeni"),
        CurrencyOption("THB", "฿", "Thai Baht"),
        CurrencyOption("TJS", "TJS", "Tajikistani Somoni"),
        CurrencyOption("TMT", "TMT", "Turkmenistani Manat"),
        CurrencyOption("TND", "DT", "Tunisian Dinar"),
        CurrencyOption("TOP", "TOP", "Tongan Paʻanga"),
        CurrencyOption("TPE", "TPE", "Timorese Escudo"),
        CurrencyOption("TRY", "₺", "Turkish Lira"),
        CurrencyOption("TTD", "TTD", "Trinidad & Tobago Dollar"),
        CurrencyOption("TWD", "NT$", "New Taiwan Dollar"),
        CurrencyOption("TZS", "TZS", "Tanzanian Shilling"),
        CurrencyOption("UAH", "₴", "Ukrainian Hryvnia"),
        CurrencyOption("UGX", "UGX", "Ugandan Shilling"),
        CurrencyOption("USD", "$", "US Dollar"),
        CurrencyOption("USN", "USN", "US Dollar (Next day)"),
        CurrencyOption("USS", "USS", "US Dollar (Same day)"),
        CurrencyOption("UYI", "UYI", "Uruguayan Peso (Indexed Units)"),
        CurrencyOption("UYU", "UYU", "Uruguayan Peso"),
        CurrencyOption("UZS", "UZS", "Uzbekistani Som"),
        CurrencyOption("VED", "VED", "Bolívar Soberano"),
        CurrencyOption("VES", "VES", "Venezuelan Bolívar"),
        CurrencyOption("VND", "₫", "Vietnamese Dong"),
        CurrencyOption("VUV", "VUV", "Vanuatu Vatu"),
        CurrencyOption("WST", "WST", "Samoan Tala"),
        CurrencyOption("XAF", "FCFA", "Central African CFA Franc"),
        CurrencyOption("XCD", "EC$", "East Caribbean Dollar"),
        CurrencyOption("XCG", "Cg.", "Caribbean guilder"),
        CurrencyOption("XOF", "F CFA", "West African CFA Franc"),
        CurrencyOption("XPF", "CFPF", "CFP Franc"),
        CurrencyOption("YER", "YER", "Yemeni Rial"),
        CurrencyOption("ZAR", "R", "South African Rand"),
        CurrencyOption("ZMW", "ZMW", "Zambian Kwacha"),
        CurrencyOption("ZWG", "ZWG", "Zimbabwean Gold"),
        CurrencyOption("ZWN", "ZWN", "ZWN"),
        CurrencyOption("ZWR", "ZWR", "Zimbabwean Dollar (2008)")
    )
}
